"""Add Announcement model for dashboard

Revision ID: 165273cc265e
Revises: 7caefd0f5610
Create Date: 2026-02-20 17:16:01.531481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165273cc265e'
down_revision = '7caefd0f5610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terminal_announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=120), nullable=False),
    sa.Column('author_title', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['terminal_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('terminal_announcements')
    # ### end Alembic commands ###
