"""Add RoomMessage for Comms chat

Revision ID: 543216266b13
Revises: 83be2f81b2d3
Create Date: 2026-02-25 18:25:22.342393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543216266b13'
down_revision = '83be2f81b2d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terminal_room_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['terminal_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['terminal_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('terminal_room_messages')
    # ### end Alembic commands ###
