"""Add Task and Meeting models for dashboard

Revision ID: 58894994d291
Revises: 56983429a759
Create Date: 2026-02-20 16:50:09.494894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58894994d291'
down_revision = '56983429a759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terminal_meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('zoom_link', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['terminal_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terminal_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['terminal_users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['terminal_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('terminal_tasks')
    op.drop_table('terminal_meetings')
    # ### end Alembic commands ###
