"""Add User team column (integer)

Revision ID: 7caefd0f5610
Revises: e2b5007cd750
Create Date: 2026-02-20 17:10:49.332091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7caefd0f5610'
down_revision = 'e2b5007cd750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terminal_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terminal_users', schema=None) as batch_op:
        batch_op.drop_column('team')

    # ### end Alembic commands ###
