"""Add Comms: Division, Team, Room, RoomMember; User division_id team_id

Revision ID: 83be2f81b2d3
Revises: b2c3d4e5f6a7
Create Date: 2026-02-25 17:19:15.098555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83be2f81b2d3'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def _table_exists(conn, name):
    r = conn.execute(sa.text(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=:n"
    ), {"n": name}).scalar()
    return r is not None


def _user_has_column(conn, col):
    r = conn.execute(sa.text("PRAGMA table_info(terminal_users)")).fetchall()
    return any(row[1] == col for row in r)


def upgrade():
    conn = op.get_bind()
    if not _table_exists(conn, "terminal_divisions"):
        op.create_table('terminal_divisions',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=120), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
    if not _table_exists(conn, "terminal_teams"):
        op.create_table('terminal_teams',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=120), nullable=False),
            sa.Column('division_id', sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(['division_id'], ['terminal_divisions.id'], name='fk_terminal_teams_division_id'),
            sa.PrimaryKeyConstraint('id')
        )
    if not _table_exists(conn, "terminal_rooms"):
        op.create_table('terminal_rooms',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=200), nullable=False),
            sa.Column('room_type', sa.String(length=32), nullable=False),
            sa.Column('division_id', sa.Integer(), nullable=True),
            sa.Column('team_id', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['division_id'], ['terminal_divisions.id'], name='fk_terminal_rooms_division_id'),
            sa.ForeignKeyConstraint(['team_id'], ['terminal_teams.id'], name='fk_terminal_rooms_team_id'),
            sa.PrimaryKeyConstraint('id')
        )
    if not _table_exists(conn, "terminal_room_members"):
        op.create_table('terminal_room_members',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('room_id', sa.Integer(), nullable=False),
            sa.Column('joined_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['room_id'], ['terminal_rooms.id'], name='fk_terminal_room_members_room_id'),
            sa.ForeignKeyConstraint(['user_id'], ['terminal_users.id'], name='fk_terminal_room_members_user_id'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('user_id', 'room_id', name='uq_room_member')
        )
    has_division_id = _user_has_column(conn, "division_id")
    has_team_id = _user_has_column(conn, "team_id")
    if not has_division_id or not has_team_id:
        with op.batch_alter_table('terminal_users', schema=None) as batch_op:
            if not has_division_id:
                batch_op.add_column(sa.Column('division_id', sa.Integer(), nullable=True))
            if not has_team_id:
                batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
    with op.batch_alter_table('terminal_users', schema=None) as batch_op:
        try:
            batch_op.create_foreign_key('fk_terminal_users_division_id', 'terminal_divisions', ['division_id'], ['id'])
        except Exception:
            pass
        try:
            batch_op.create_foreign_key('fk_terminal_users_team_id', 'terminal_teams', ['team_id'], ['id'])
        except Exception:
            pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terminal_users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_terminal_users_team_id', type_='foreignkey')
        batch_op.drop_constraint('fk_terminal_users_division_id', type_='foreignkey')
        batch_op.drop_column('team_id')
        batch_op.drop_column('division_id')

    op.drop_table('terminal_room_members')
    op.drop_table('terminal_rooms')
    op.drop_table('terminal_teams')
    op.drop_table('terminal_divisions')
    # ### end Alembic commands ###
