"""Add User watchlist for Live Market tickers

Revision ID: e2b5007cd750
Revises: 58894994d291
Create Date: 2026-02-20 17:07:38.177384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b5007cd750'
down_revision = '58894994d291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terminal_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('watchlist', sa.String(length=120), nullable=True))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terminal_users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.drop_column('watchlist')

    # ### end Alembic commands ###
